// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnRDBPHijtdquoH1f-jV5kdTbW0i9GtfQ',
    appId: '1:766295802955:web:e5cd9e0f0e9e3a6e32b9ce',
    messagingSenderId: '766295802955',
    projectId: 'playtime-87606',
    authDomain: 'playtime-87606.firebaseapp.com',
    storageBucket: 'playtime-87606.firebasestorage.app',
    measurementId: 'G-44D6P5BDTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa92xdrDunLMHkUG7Q0GZVVvgPniBEr7A',
    appId: '1:766295802955:android:f55f11e14832980032b9ce',
    messagingSenderId: '766295802955',
    projectId: 'playtime-87606',
    storageBucket: 'playtime-87606.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcaUPLOXjpEHZ_HZ-XNDGgjUW-OemWeTE',
    appId: '1:766295802955:ios:30fb988290e7fb2c32b9ce',
    messagingSenderId: '766295802955',
    projectId: 'playtime-87606',
    storageBucket: 'playtime-87606.firebasestorage.app',
    iosBundleId: 'com.example.playtime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcaUPLOXjpEHZ_HZ-XNDGgjUW-OemWeTE',
    appId: '1:766295802955:ios:30fb988290e7fb2c32b9ce',
    messagingSenderId: '766295802955',
    projectId: 'playtime-87606',
    storageBucket: 'playtime-87606.firebasestorage.app',
    iosBundleId: 'com.example.playtime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnRDBPHijtdquoH1f-jV5kdTbW0i9GtfQ',
    appId: '1:766295802955:web:7a59b1e53272dd1532b9ce',
    messagingSenderId: '766295802955',
    projectId: 'playtime-87606',
    authDomain: 'playtime-87606.firebaseapp.com',
    storageBucket: 'playtime-87606.firebasestorage.app',
    measurementId: 'G-JEVJZ54J50',
  );
}
